### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by andy-sww** [andy-sww/re_model#2]
- [ ] Pic Handling andy-sww/page_builder#2 
- [x] Asset Handling andy-sww/page_builder#7 
- [x] Base folder functionality
- [x] UI Design
- [x] Basic Output rendering
- [ ] Selecting & Transfering of Base Assets
- [x] Meta Transfer andy-sww/page_builder#13 
- [x] Content Transfer andy-sww/page_builder#13 
- [ ] Templating Helpers
- [ ] Fonts to Assets
- [x] Auto-select links
- [x] User Settings andy-sww/page_builder#14 
- [x] Clean up output folder before rendering
- [ ] JS Handling

**Comment by andy-sww** [comment]
[Templating Helpers] fixed with 2c1994c3545a538e89a52dfe0c9fb62a66b2905c

**Comment by andy-sww** [comment]
[Decode Special Chars] fixed with 15f53c2b9125ec7b1b19acb1d3b536fffca1fc68

**Comment by andy-sww** [comment]
[Default Preview Window Size] fixed with 79a3d4dc39c7db972c0e48beec4df7e10cfcdca1
